- name: Check endpoint
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Check url
      uri:
        url: http://172.30.197.156:8080/datacatalog/hello2
        status_code: 404
    - name: Check url 2
      uri:
        url: http://172.30.197.156:8080/datacatalog/hello
        status_code: 200
        