- name: create tomcat server
  hosts: all
  tasks:
    - name: Download Tomcat
      get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz dest=~/apache-tomcat-7.0.61.tar.gz

    - name: Extract archive
      unarchive:
        src: ~/apache-tomcat-7.0.61.tar.gz
        dest: ~/

    - name: Start Tomcat
      service: name=tomcat state=started enabled=yes

    - name: wait for tomcat to start
      wait_for: port=8080