- name: create apache server
  hosts: all
  tasks:
    - name: Install http and php etc
      yum: name={{ item }} state=present
      with_items:
      - httpd

    - name: Start Apache
      service: name=httpd state=started enabled=yes