- name: create apache server
  hosts: all
  tasks:
    - name: Install http and php etc
      yum: name=['httpd'] state=present
      become: true

    - name: Start Apache
      service: name=httpd state=started enabled=yes